Created Sign In Fragment with Layout
sasisachin12/SQLRoomSample pull request #14
Opened 2022-09-19 17:15 UTC by nwaeme-olise

# Description

Created a sign in screen composed of the required widgets (edit texts and button)

## Type of change

- [ ] New feature 

# Checklist:

- [ ] Checked code analyze and clean up
- [ ] Followed standard code styles

## Screenshot

2022-09-20 03:13 UTC, EQua-Dev commented on app/src/main/java/aaa/app/android/sqlroomsample/fragments/SignInFragment.kt
> +
Could you use view binding to fetch the data from the XML as opposed to the soon deprecated android-extensions

2022-09-20 03:29 UTC, EQua-Dev requested changes
Kindly address the various change requests and attach a screenshot of the running app or from the Android studio code editor for visuals. Good job so far 👍🏾

2022-09-20 03:29 UTC, EQua-Dev commented on app/src/main/java/aaa/app/android/sqlroomsample/fragments/SignInFragment.kt
> +
Could you kindly use view binding to fetch the data from the XML to make the layout input data available for use

2022-09-20 03:29 UTC, EQua-Dev commented on app/src/main/res/layout/fragment_sign_in.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
It would be nice to see a screenshot of the designed layout

2022-09-20 03:29 UTC, EQua-Dev commented on app/src/main/res/values/strings.xml
>  </resources>
kindly consider the naming convention, if the string is used for a button in a particular layout, it would be nice to state so in the name 🙂

2022-09-20 03:29 UTC, EQua-Dev commented on app/src/main/res/layout/fragment_sign_in.xml
> +
kindly include a text view to allow the user navigate to sign up if they don't have an account

2022-09-20 03:29 UTC, EQua-Dev commented on app/src/main/res/layout/fragment_sign_in.xml
>          android:layout_marginTop="30dp"
kindly define this in the dime file and call it from there instead

2022-09-20 03:40 UTC, nwaeme-olise commented on app/src/main/java/aaa/app/android/sqlroomsample/fragments/SignInFragment.kt
> +
Alright boss, will do. Thanks

2022-09-20 03:40 UTC, nwaeme-olise commented on app/src/main/java/aaa/app/android/sqlroomsample/fragments/SignInFragment.kt
> +
Alright boss, will do. Thanks

2022-09-20 03:44 UTC, nwaeme-olise commented on app/src/main/res/layout/fragment_sign_in.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
Tried uploading one when creating the PR but it wasn't working 
![Screenshot_20220919-180300_Expense Calculator](https://user-images.githubusercontent.com/35772751/191162736-c44b7e6d-7f43-4750-b5ae-3044b84c37b5.jpg)

2022-09-20 03:54 UTC, EQua-Dev commented
Oh Ok.
Cool!

Try making the login button color to be 'colorPrimary'



On Tue, 20 Sept 2022 at 04:44, Nwaeme Olisemeka ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In app/src/main/res/layout/fragment_sign_in.xml
> <https://github.com/sasisachin12/SQLRoomSample/pull/14#discussion_r974858047>
> :
>
> > +        android:layout_width="0dp"
> +        android:layout_height="wrap_content"
> +        android:layout_marginTop="30dp"
> +        ***@***.***/round_button"
> +        ***@***.***/button_save"
> +        ***@***.***/buttonLabel"
> +        app:layout_constraintEnd_toEndOf="@+id/edit_text_password"
> +        app:layout_constraintStart_toStartOf="@+id/edit_text_password"
> +        ***@***.***/edit_text_password" />
> +
> +
> +
> +
> +
> +
> +</androidx.constraintlayout.widget.ConstraintLayout>
>
> Tried uploading one when creating the PR but it wasn't working
> [image: Screenshot_20220919-180300_Expense Calculator]
> <https://user-images.githubusercontent.com/35772751/191162736-c44b7e6d-7f43-4750-b5ae-3044b84c37b5.jpg>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sasisachin12/SQLRoomSample/pull/14#discussion_r974858047>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKMIM4DZJMRMLCMZV2TOC4LV7EXKHANCNFSM6AAAAAAQQJTGPE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-09-20 03:54 UTC, EQua-Dev commented
Good job bro!

👍🏾

On Tue, 20 Sept 2022 at 04:54, Richard Uzor ***@***.***> wrote:

> Oh Ok.
> Cool!
>
> Try making the login button color to be 'colorPrimary'
>
>
>
> On Tue, 20 Sept 2022 at 04:44, Nwaeme Olisemeka ***@***.***>
> wrote:
>
>> ***@***.**** commented on this pull request.
>> ------------------------------
>>
>> In app/src/main/res/layout/fragment_sign_in.xml
>> <https://github.com/sasisachin12/SQLRoomSample/pull/14#discussion_r974858047>
>> :
>>
>> > +        android:layout_width="0dp"
>> +        android:layout_height="wrap_content"
>> +        android:layout_marginTop="30dp"
>> +        ***@***.***/round_button"
>> +        ***@***.***/button_save"
>> +        ***@***.***/buttonLabel"
>> +        app:layout_constraintEnd_toEndOf="@+id/edit_text_password"
>> +        app:layout_constraintStart_toStartOf="@+id/edit_text_password"
>> +        ***@***.***/edit_text_password" />
>> +
>> +
>> +
>> +
>> +
>> +
>> +</androidx.constraintlayout.widget.ConstraintLayout>
>>
>> Tried uploading one when creating the PR but it wasn't working
>> [image: Screenshot_20220919-180300_Expense Calculator]
>> <https://user-images.githubusercontent.com/35772751/191162736-c44b7e6d-7f43-4750-b5ae-3044b84c37b5.jpg>
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/sasisachin12/SQLRoomSample/pull/14#discussion_r974858047>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AKMIM4DZJMRMLCMZV2TOC4LV7EXKHANCNFSM6AAAAAAQQJTGPE>
>> .
>> You are receiving this because you commented.Message ID:
>> ***@***.***>
>>
>

2022-09-20 18:20 UTC, sasisachin12 requested changes
Dont commit .idea/ files . keep it local

2022-09-20 23:14 UTC, fukimusap commented on app/src/main/res/layout/fragment_sign_in.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
should the user be able to see our navigation bar if they are not signed in or that is addressed in a follow up MR?

2022-09-20 23:16 UTC, fukimusap commented on build.gradle
> +        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10"
what is` $kotlin_version? `can we update the version there instead?

2022-09-20 23:19 UTC, fukimusap reviewed
- [ ] Don't forget to revert the files in the .idea folder

2022-09-21 02:58 UTC, EQua-Dev commented on app/src/main/res/layout/fragment_sign_in.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
> should the user be able to see our navigation bar if they are not signed in or that is addressed in a follow up MR?

it will be addressed in a follow up MR, including removing the action bar in the authentication screens

2022-09-21 03:06 UTC, EQua-Dev reviewed
@fooksm said something about defining the Kotlin version in the project level gradle file instead. Every other thing looks ok from my end. 👍🏾

2023-07-29 07:05 UTC, closed without merging