Fixed report screen activity
sasisachin12/SQLRoomSample pull request #8
Opened 2022-09-18 15:50 UTC by ashu-sa

Fixed Report Screen fragment and Expense screen fragment

2022-09-18 17:03 UTC, sasisachin12 requested changes

2022-09-18 17:03 UTC, sasisachin12 commented on app/src/main/java/aaa/app/android/sqlroomsample/fragments/ExpenseListFragment.kt
> +            val totalAmount: Long = expenseList.sumOf { it.amount.toLong() }
can you please change data type as  float here and also 
restrict input value above 6 char in the expanse amount.

2022-09-18 17:03 UTC, sasisachin12 commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_11" default="true" project-jdk-name="11" project-jdk-type="JavaSDK">
Please remove this file . keep it local.  i will add this git ignore

2022-09-18 17:03 UTC, sasisachin12 commented on app/src/main/java/aaa/app/android/sqlroomsample/fragments/ExpenseFragment.kt
> +            if (expense_for.text!!.isNotEmpty() && expense_amount.text!!.isNotEmpty()){
is this condition is required?

2022-09-18 17:09 UTC, ashu-sa commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_11" default="true" project-jdk-name="11" project-jdk-type="JavaSDK">
Okay

2022-09-18 17:09 UTC, ashu-sa commented on app/src/main/java/aaa/app/android/sqlroomsample/fragments/ExpenseFragment.kt
> +            if (expense_for.text!!.isNotEmpty() && expense_amount.text!!.isNotEmpty()){
Yes, otherwise when we back to Home screen it pops up the toast

2022-09-18 17:10 UTC, ashu-sa commented on app/src/main/java/aaa/app/android/sqlroomsample/fragments/ExpenseListFragment.kt
> +            val totalAmount: Long = expenseList.sumOf { it.amount.toLong() }
Okay

2022-09-20 23:07 UTC, fukimusap commented on app/src/main/java/aaa/app/android/sqlroomsample/fragments/ExpenseFragment.kt
> +                    "Expense Added Successfully",
can we edit the original string resource with the new text?

2022-11-01 05:54 UTC, sasisachin12 commented
Because of conflicts closed this MR

2022-11-01 05:54 UTC, closed without merging